baseURL = "https://www.bogste.ro"
languageCode = "en-us"
theme = "personal-web"

title = "Ian Bog'Ste - Personal Website"
copyright="© Ian Bog'Ste 2021-..."

enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

# See and Enable below [rivacy.googleAnalytics]
googleAnalytics = "G-YJLC0DJ1QV"

[params.intro]
  main = "Hi :wave:, I am Ian Bog'Ste"
  sub = "A former SDE turned to Engineering Manager"

[params.main]
  latestPublishHeader = "Latest Updates"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['posts'] # values: ['posts', 'photography', 'portfolio'] only accept one section, to be displayed below in Home and 404
  secondarySections = ['photography']

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"
  photography = "photography project"

[params.sidebar]
  backgroundImage = '/images/sidebar/blog_sidebar.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = 'rgba(0,0,0,0.4),rgba(0,0,0,0.75)' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/bogste-profile-photo-500px.png" # - default "/images/edna-west.jpg"

[params.assets]
  favicon = "/favicon.ico"
  customCSS = ""

[params.social]
  linkedin = "https://www.linkedin.com/in/bogste"
  github = "https://github.com/bogste"
  twitter = "https://twitter.com/b0gste"
  keybase = "https://keybase.io/b0gste"
  #medium = "https://medium.com/"
  #codepen = "https://codepen.io/"
  #facebook = "https://www.facebook.com/"
  #youtube = "https://www.youtube.com/"
  #instagram = "https://www.instagram.com/"
  #gitlab = "https://gitlab.com/"

[params.contact]
  email = "ian.bogste@keemail.me"
  text= "Email me!" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "navmenu-home-page"
  name = "Home"
  title = "Navigate to Home page"
  url = "/"
  weight = -200

[[menu.main]]
  identifier = "navmenu-blog-page"
  name = "My Blog"
  title = "Navigate to Blog section"
  url = "/posts/#content"
  weight = -150

  [[menu.main]]
    identifier = "navmenu-photography"
    name = "Photography"
    title = "Navigate to my Photography Projects portfolio"
    url = "/photography/#content"
    weight = -130

  [[menu.main]]
    identifier = "navmenu-about-page"
    name = "About me"
    title = "Navigate to About me page"
    url = "/about/#content"
    weight = -120

# [[menu.main]]
#   identifier = "navmenu-portfolio"
#   name = "Projects"
#   title = "Navigate to my Projects portfolio"
#   url = "/portfolio/"
#   weight = -100


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false

  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
