baseURL = "https://bogste.ro"
languageCode = "en-us"
title = "Ian Bog`Ste's Personal Site"
theme = "personal-web"
copyright="© Ian Bog`Ste 2021-..."
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, :wave:  I'm Ian Bog`Ste"
  sub = "I'm a former SDE turned to Engineering Manager"

[params.main]
  latestPublishHeader = "Latest Updates:"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['posts'] # values: ['posts', 'photography', 'portfolio'] only accept one section, to be displayed below in Home and 404
  secondarySections = ['none']

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"
  photography = "photography project"

[params.sidebar]
  backgroundImage = '/images/sidebar/blog_sidebar.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = 'rgba(0,0,0,0.4),rgba(0,0,0,0.75)' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/bogste-profile-photo.svg" # - default "/images/edna-west.jpg"

[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  linkedin = "https://www.linkedin.com/in/bogste"
  github = "https://github.com/bogste"
  twitter = "https://twitter.com/b0gste"
  keybase = "https://keybase.io/b0gste"
  #medium = "https://medium.com/"
  #codepen = "https://codepen.io/"
  #facebook = "https://www.facebook.com/"
  #youtube = "https://www.youtube.com/"
  #instagram = "https://www.instagram.com/"
  #gitlab = "https://gitlab.com/"

[params.contact]
  email = "ian.bogste@keemail.me"
  text= "Email me!" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About me"
  title = "About me"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog section"
  url = "/posts/"
  weight = -110

# [[menu.main]]
#   identifier = "portfolio"
#   name = "Projects"
#   title = "Projects portfolio"
#   url = "/portfolio/"
#   weight = -100
#
# [[menu.main]]
#   identifier = "photography"
#   name = "Photography"
#   title = "Photography Projects portfolio"
#   url = "/photography/"
#   weight = -90

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
